### CRIAR usuário
POST http://localhost:3010/users
Content-Type: application/json

{
  "name": "user",
  "email": "usua@email.com",
  "senha": "123",
  "cargo": "gerente"
}

### LISTAR todos
GET http://localhost:3010/users

### ATUALIZAR (PUT)
PUT http://localhost:3010/users/2f72b345-1135-4bbd-84af-844783903ce8
Content-Type: application/json

{
  "name": "Ana Silva",
  "email": "ana@email.com",
  "senha": "1234",
  "cargo": "supervisor"
}

### DELETAR
DELETE http://localhost:3010/users/94d860d4-ccbe-48c2-b230-6ffc798a6536

### Enviar
GET http://localhost:3010/equipamentos


### CRIAR usuário
POST http://localhost:3010/manutencoes
Content-Type: application/json

{
    "equipamento_id": "d8e16f11-5e76-4547-bdb3-d97771423a6d" ,
    "data_manutencao": "2025-07-31",
    "status": "pendente",
    "responsavel_id": "d51db308-df69-4390-9322-70de55061df0"
}

### LISTAR todos
GET http://localhost:3010/manutencoes